name: Authen-TypeKey
version: 0.01
abstract: TypeKey Authentication
author: Six Apart <cpan@sixapart.com>
license: perl
distribution_type: module
requires:
  Crypt::DSA: 0
  MIME::Base64: 0
  LWP: 0
no_index:
  directory:
    - t
    - inc
generated_by: Module::Install version 0.33
